In [1]:
import numpy as np

In [2]:
import colarray as ca

# Colarray

In [3]:
help(ca.colarray)

Help on class colarray in module colarray:

class colarray(builtins.object)
 |  colarray(column_names, size, dtype=<class 'numpy.float32'>)
 |  
 |  A container class storing several sets ('columns') of data with identical dimensions in a single numpy array. Strings are used as indicies along the zeroth dimension corresponding to different columns of data. 
 |  
 |  Storage for positions, velocities, and forces, for 1000 particles in 2 dimensions:
 |  >>> ca = colarray(('r', 'v', 'f'), size=(1000,2))
 |  >>> ca.shape
 |  (3, 1000, 2)
 |  
 |  >>> ca.column_names
 |  ('r', 'v', 'f')
 |  
 |  Data is accesed via string indicies (similar to dataframes in pandas):
 |  >>> ca['r'] = np.ones((1000,2))
 |  >>> ca['v'] = 2
 |  >>> print(ca['r'] + 0.01*ca['v'])
 |  [[1.02 1.02]
 |   [1.02 1.02]
 |   [1.02 1.02]
 |   ...
 |   [1.02 1.02]
 |   [1.02 1.02]
 |   [1.02 1.02]]
 |   
 |  Assignment have to be with an existing key (as opposed to eg. pandas): 
 |  >>> ca['c'] = 1
 |  Traceback (most rec

# Example

In [4]:
x = ca.colarray(('a', 'b'), (1000,3))

In [5]:
x.shape

(2, 1000, 3)

In [6]:
help(ca.save)

Help on function save in module colarray:

save(file, colarray)
    Save a colarray to disk.
    >>> ca = colarray(('r', 'v', 'f'), size=(1000,2))
    >>> save('test_colarray', ca)



In [7]:
x.column_names

('a', 'b')

In [8]:
x.dtype

numpy.float32

In [16]:
x['a'] = np.ones((1000,3))
x['b'] = np.random.uniform(size=(1000,3))
x

colarray(('a', 'b'), (1000, 3))
array([[[1.        , 1.        , 1.        ],
        [1.        , 1.        , 1.        ],
        [1.        , 1.        , 1.        ],
        ...,
        [1.        , 1.        , 1.        ],
        [1.        , 1.        , 1.        ],
        [1.        , 1.        , 1.        ]],

       [[0.2176669 , 0.07019886, 0.05320156],
        [0.21662939, 0.5119017 , 0.1647396 ],
        [0.55108464, 0.16708784, 0.00101788],
        ...,
        [0.8725542 , 0.2981146 , 0.35043624],
        [0.3227727 , 0.15002614, 0.6740579 ],
        [0.07129676, 0.05251902, 0.6670916 ]]], dtype=float32)

In [10]:
c = ca.colarray(('x', 'v', 'f'), size=(1000,2))
c['x'] = np.ones((1000,2))
c['v'] = 2. 
print(c['x'] + 0.01*c['v'])

[[1.02 1.02]
 [1.02 1.02]
 [1.02 1.02]
 ...
 [1.02 1.02]
 [1.02 1.02]
 [1.02 1.02]]


In [13]:
c2 = ca.load('test_colarray')
c2

colarray(('r', 'v', 'f'), (1000, 2))
array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        ...,
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        ...,
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        ...,
        [0., 0.],
        [0., 0.],
        [0., 0.]]], dtype=float32)

In [14]:
np.load('test_colarray.npy')

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        ...,
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        ...,
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        ...,
        [0., 0.],
        [0., 0.],
        [0., 0.]]], dtype=float32)

In [12]:
!pwd

/home/tbs/Python/Projects/gamdpy


In [17]:
for col in c.column_names:
    print(np.all(c[col]==c2[col]))

True
True
True


In [13]:
b.sa

AttributeError: 'numpy.ndarray' object has no attribute 'sa'

# Error handling (relying on np.array)

colarray is a thin layer on top of numpy.array, so most error handling is left to numpy. As illustrated below, this gives usefull error messages.

In [14]:
x['a'] = np.ones((100,3))

ValueError: could not broadcast input array from shape (100,3) into shape (1000,3)

In [15]:
x['c'] = 1

KeyError: 'c'

In [11]:
columns = ('a', 'b', 'c', 'd')
columns

('a', 'b', 'c', 'd')

In [13]:
columns[:2]

('a', 'b')

In [14]:
columns[2:]

('c', 'd')

In [15]:
col = 1
columns[:col]+columns[col+1:]

('a', 'c', 'd')

In [16]:
print(columns)

('a', 'b', 'c', 'd')


In [17]:
for key in columns:
    print(key)

a
b
c
d


In [17]:
x = np.array((1, 2, 3, 4))
x

array([1, 2, 3, 4])

In [20]:
type(x)==np.ndarray

True